# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: service.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import core_pb2 as core__pb2
import fs_pb2 as fs__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rservice.proto\x12\x16OCA.Cloud_Py_API.Proto\x1a\ncore.proto\x1a\x08\x66s.proto2\xb0\x06\n\x0e\x43loudPyApiCore\x12T\n\x08TaskExit\x12\'.OCA.Cloud_Py_API.Proto.TaskExitRequest\x1a\x1d.OCA.Cloud_Py_API.Proto.Empty\"\x00\x12R\n\x07TaskLog\x12&.OCA.Cloud_Py_API.Proto.TaskLogRequest\x1a\x1d.OCA.Cloud_Py_API.Proto.Empty\"\x00\x12\\\n\tFsGetInfo\x12(.OCA.Cloud_Py_API.Proto.FsGetInfoRequest\x1a#.OCA.Cloud_Py_API.Proto.FsListReply\"\x00\x12V\n\x06\x46sList\x12%.OCA.Cloud_Py_API.Proto.FsListRequest\x1a#.OCA.Cloud_Py_API.Proto.FsListReply\"\x00\x12X\n\x06\x46sRead\x12%.OCA.Cloud_Py_API.Proto.FsReadRequest\x1a#.OCA.Cloud_Py_API.Proto.FsReadReply\"\x00\x30\x01\x12\\\n\x08\x46sCreate\x12\'.OCA.Cloud_Py_API.Proto.FsCreateRequest\x1a%.OCA.Cloud_Py_API.Proto.FsCreateReply\"\x00\x12V\n\x07\x46sWrite\x12&.OCA.Cloud_Py_API.Proto.FsWriteRequest\x1a\x1f.OCA.Cloud_Py_API.Proto.FsReply\"\x00(\x01\x12V\n\x08\x46sDelete\x12\'.OCA.Cloud_Py_API.Proto.FsDeleteRequest\x1a\x1f.OCA.Cloud_Py_API.Proto.FsReply\"\x00\x12V\n\x06\x46sMove\x12%.OCA.Cloud_Py_API.Proto.FsMoveRequest\x1a#.OCA.Cloud_Py_API.Proto.FsMoveReply\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'service_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _CLOUDPYAPICORE._serialized_start=64
  _CLOUDPYAPICORE._serialized_end=880
# @@protoc_insertion_point(module_scope)
