<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: core.proto

namespace OCA\NC_GRPC_Example\Proto;

if (false) {
    /**
     * This class is deprecated. Use OCA\NC_GRPC_Example\Proto\CheckDataRequest\installed_pckg instead.
     * @deprecated
     */
    class CheckDataRequest_installed_pckg {}
}
class_exists(CheckDataRequest\installed_pckg::class);
@trigger_error('OCA\NC_GRPC_Example\Proto\CheckDataRequest_installed_pckg is deprecated and will be removed in the next major release. Use OCA\NC_GRPC_Example\Proto\CheckDataRequest\installed_pckg instead', E_USER_DEPRECATED);

