<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: core.proto

namespace OCA\NC_GRPC_Example\Proto;

if (false) {
    /**
     * This class is deprecated. Use OCA\NC_GRPC_Example\Proto\TaskInitReply\cfgOptions instead.
     * @deprecated
     */
    class TaskInitReply_cfgOptions {}
}
class_exists(TaskInitReply\cfgOptions::class);
@trigger_error('OCA\NC_GRPC_Example\Proto\TaskInitReply_cfgOptions is deprecated and will be removed in the next major release. Use OCA\NC_GRPC_Example\Proto\TaskInitReply\cfgOptions instead', E_USER_DEPRECATED);

