<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: core.proto

namespace OCA\NC_GRPC_Example\Proto;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>OCA.NC_GRPC_Example.Proto.TaskInitReply</code>
 */
class TaskInitReply extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.OCA.NC_GRPC_Example.Proto.taskType cmdType = 1;</code>
     */
    protected $cmdType = 0;
    /**
     * Name of the app. Installed packages will be stored by this name for app.
     *
     * Generated from protobuf field <code>string appName = 2;</code>
     */
    protected $appName = '';
    /**
     * Path to module root, to be executed.
     *
     * Generated from protobuf field <code>string modPath = 3;</code>
     */
    protected $modPath = '';
    /**
     * Which function to execute.
     *
     * Generated from protobuf field <code>string funcName = 4;</code>
     */
    protected $funcName = '';
    /**
     * Optional arguments to pass to target python app's module.
     *
     * Generated from protobuf field <code>repeated string args = 5;</code>
     */
    private $args;
    /**
     * Generated from protobuf field <code>.OCA.NC_GRPC_Example.Proto.TaskInitReply.cfgOptions config = 6;</code>
     */
    protected $config = null;
    /**
     * Database configuration
     *
     * Generated from protobuf field <code>.OCA.NC_GRPC_Example.Proto.dbConfig dbCfg = 7;</code>
     */
    protected $dbCfg = null;
    /**
     * PHP Callback handler for TaskExit
     *
     * Generated from protobuf field <code>string handler = 8;</code>
     */
    protected $handler = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $cmdType
     *     @type string $appName
     *           Name of the app. Installed packages will be stored by this name for app.
     *     @type string $modPath
     *           Path to module root, to be executed.
     *     @type string $funcName
     *           Which function to execute.
     *     @type string[]|\Google\Protobuf\Internal\RepeatedField $args
     *           Optional arguments to pass to target python app's module.
     *     @type \OCA\NC_GRPC_Example\Proto\TaskInitReply\cfgOptions $config
     *     @type \OCA\NC_GRPC_Example\Proto\dbConfig $dbCfg
     *           Database configuration
     *     @type string $handler
     *           PHP Callback handler for TaskExit
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Core::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.OCA.NC_GRPC_Example.Proto.taskType cmdType = 1;</code>
     * @return int
     */
    public function getCmdType()
    {
        return $this->cmdType;
    }

    /**
     * Generated from protobuf field <code>.OCA.NC_GRPC_Example.Proto.taskType cmdType = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setCmdType($var)
    {
        GPBUtil::checkEnum($var, \OCA\NC_GRPC_Example\Proto\taskType::class);
        $this->cmdType = $var;

        return $this;
    }

    /**
     * Name of the app. Installed packages will be stored by this name for app.
     *
     * Generated from protobuf field <code>string appName = 2;</code>
     * @return string
     */
    public function getAppName()
    {
        return $this->appName;
    }

    /**
     * Name of the app. Installed packages will be stored by this name for app.
     *
     * Generated from protobuf field <code>string appName = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setAppName($var)
    {
        GPBUtil::checkString($var, True);
        $this->appName = $var;

        return $this;
    }

    /**
     * Path to module root, to be executed.
     *
     * Generated from protobuf field <code>string modPath = 3;</code>
     * @return string
     */
    public function getModPath()
    {
        return $this->modPath;
    }

    /**
     * Path to module root, to be executed.
     *
     * Generated from protobuf field <code>string modPath = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setModPath($var)
    {
        GPBUtil::checkString($var, True);
        $this->modPath = $var;

        return $this;
    }

    /**
     * Which function to execute.
     *
     * Generated from protobuf field <code>string funcName = 4;</code>
     * @return string
     */
    public function getFuncName()
    {
        return $this->funcName;
    }

    /**
     * Which function to execute.
     *
     * Generated from protobuf field <code>string funcName = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setFuncName($var)
    {
        GPBUtil::checkString($var, True);
        $this->funcName = $var;

        return $this;
    }

    /**
     * Optional arguments to pass to target python app's module.
     *
     * Generated from protobuf field <code>repeated string args = 5;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getArgs()
    {
        return $this->args;
    }

    /**
     * Optional arguments to pass to target python app's module.
     *
     * Generated from protobuf field <code>repeated string args = 5;</code>
     * @param string[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setArgs($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->args = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.OCA.NC_GRPC_Example.Proto.TaskInitReply.cfgOptions config = 6;</code>
     * @return \OCA\NC_GRPC_Example\Proto\TaskInitReply\cfgOptions
     */
    public function getConfig()
    {
        return $this->config;
    }

    /**
     * Generated from protobuf field <code>.OCA.NC_GRPC_Example.Proto.TaskInitReply.cfgOptions config = 6;</code>
     * @param \OCA\NC_GRPC_Example\Proto\TaskInitReply\cfgOptions $var
     * @return $this
     */
    public function setConfig($var)
    {
        GPBUtil::checkMessage($var, \OCA\NC_GRPC_Example\Proto\TaskInitReply_cfgOptions::class);
        $this->config = $var;

        return $this;
    }

    /**
     * Database configuration
     *
     * Generated from protobuf field <code>.OCA.NC_GRPC_Example.Proto.dbConfig dbCfg = 7;</code>
     * @return \OCA\NC_GRPC_Example\Proto\dbConfig
     */
    public function getDbCfg()
    {
        return $this->dbCfg;
    }

    /**
     * Database configuration
     *
     * Generated from protobuf field <code>.OCA.NC_GRPC_Example.Proto.dbConfig dbCfg = 7;</code>
     * @param \OCA\NC_GRPC_Example\Proto\dbConfig $var
     * @return $this
     */
    public function setDbCfg($var)
    {
        GPBUtil::checkMessage($var, \OCA\NC_GRPC_Example\Proto\dbConfig::class);
        $this->dbCfg = $var;

        return $this;
    }

    /**
     * PHP Callback handler for TaskExit
     *
     * Generated from protobuf field <code>string handler = 8;</code>
     * @return string
     */
    public function getHandler()
    {
        return $this->handler;
    }

    /**
     * PHP Callback handler for TaskExit
     *
     * Generated from protobuf field <code>string handler = 8;</code>
     * @param string $var
     * @return $this
     */
    public function setHandler($var)
    {
        GPBUtil::checkString($var, True);
        $this->handler = $var;

        return $this;
    }

}

