<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: core.proto

namespace GPBMetadata;

class Core
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0a9c020a0a636f72652e70726f746f120f4e435f475250435f4578616d706c6522070a05456d707479220f0a0d5461736b496e69745265706c7922210a0f5461736b4578697452657175657374120e0a06726573756c74180120012809225b0a0e5461736b4c6f675265717565737412280a076c6f675f6c766c18012001280e32172e4e435f475250435f4578616d706c652e6c6f674c766c120e0a066d6f64756c65180220012809120f0a07636f6e74656e741803200328092a3d0a066c6f674c766c12090a054445425547100012080a04494e464f100112080a045741524e100212090a054552524f52100312090a05464154414c1004421cca02194f43415c4e435f475250435f4578616d706c655c50726f746f620670726f746f33"
        ), true);

        static::$is_initialized = true;
    }
}

