name: Test grpc

on:
  pull_request:
    paths:
      - '.github/workflows/test-grpc.yml'
      - 'docker/*.Dockerfile'
  push:
    branches: [master]
    paths:
      - '.github/workflows/test-grpc.yml'
      - 'docker/*.Dockerfile'
  workflow_dispatch:

jobs:
  p_o_c:
    runs-on: ubuntu-22.04
    name: ${{ matrix.docker_file }}

    strategy:
      fail-fast: false
      matrix:
        docker_file: ["Ubuntu_22_04"]

    steps:
      - uses: actions/checkout@v3
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Requirements
        uses: docker/build-push-action@v4
        with:
          context: .
          file: docker/${{ matrix.docker_file }}.Dockerfile
          push: false
          cache-from: type=gha,scope=${{ matrix.docker_file }}
          cache-to: type=gha,mode=max,scope=${{ matrix.docker_file }}
          target: base

      - name: Proof of Concept
        uses: docker/build-push-action@v4
        with:
          context: .
          file: docker/${{ matrix.docker_file }}.Dockerfile
          push: false
          target: proof_of_concept
